name: Push branch
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test